### ISSUE TITLE
Add LTE support

### ISSUE THREAD

**Issue by linushstge** [rickyzhang82/tethering#14]
Works fine with connected Wi-Fi on iOS, but i can't use my LTE connection as the proxy endpoint.

Any ideas how to solve this?

Goal:
- Use iPhone tethering via USB
- iOS Socks Proxy using mobile LTE

Mac OS -> Socks Proxy on iPhone via USB network -> LTE

kind regards Linus

**Comment by rickyzhang82** [comment]
Sorry, I don't know how to do it, either. I'd recommend you to buy a portable wifi router. See my user guide. It is cheap. You can share LTE connection to many devices.
