### ISSUE TITLE
More of a Question than an issue iOS 9.0 support 

### ISSUE THREAD

**Issue by gh0sti** [rickyzhang82/tethering#16]
I havent compiled it yet but does this app work on iOS 9.x+?

**Comment by greatquux** [comment]
It worked for me on 9.1 (haven't tested since then).

Sent from my mobile phone

On Jan 21, 2016, at 11:42 AM, gh0sti <notifications@github.com<mailto:notifications@github.com>> wrote:


I havent compiled it yet but does this app work on iOS 9x+?

**Comment by gh0sti** [comment]
@greatquux can you allow other devices to tether to it for example a smart tv? Im just thinking of possibly unjailbreaking to allow this, also how does it look on newer devices say iPhone 6 and onward

**Comment by gh0sti** [comment]
@greatquux could I actually setup a wireless router to connect to my phone to produce the tethering?

**Comment by greatquux** [comment]
What this does is run a SOCKS proxy server on your phone. So you would need your smart tv or whatever other client you've got to have SOCKS proxy client support. Although I only tested this in ad-hoc wireless mode, I think it will work as long as both the phone and the client are on the same wireless network. 
Only issue is, if your wireless router has a route to the Internet, when the phone connects it will use this route preferentially over the LTE, so even if your client connects to the SOCKS proxy, the phone will just send the traffic out the wifi router's gateway.  So your wireless router that makes the network would have to be configured without an internet connection, maybe a wireless access point would be better for this.

**Comment by OldManFern** [comment]
To answer original question i compiled and installed it to 9.2 and it didn't work for me. I don't have any free time so I haven't looked through the code. It runs on phone and i can connect to it but nothing is sent over network. I will try to figure out the problem later. I was hoping someone had functional code already working for 9.2

**Comment by optimoid** [comment]
I haven't had any problems with the app compiled against the 9.2 SDK and run on iOS 9.2.1.

I'd be interested to hear more details @OldManFern.

**Comment by OldManFern** [comment]
Wait do you not get this after compile?
<img width="253" alt="screen shot 2016-01-30 at 11 55 50 am" src="https://cloud.githubusercontent.com/assets/9030140/12698086/76a5ba28-c748-11e5-867f-2fd2a1de76b7.png">

**Comment by optimoid** [comment]
Most of those warnings are in logging functions which aren't called. They should all be fixed but I found that the app still compiles and runs correctly.

**Comment by OldManFern** [comment]
Thats what i thought since most of it is just Unused or doesn't matter for running. But Since it didn't work for me on. I will try it again later and try debugging and find where the issues. Or even better it will just work.

**Comment by OldManFern** [comment]
Hello, so I tried running it again compiled with the changes you made. But still not functional. On the app on phone it says it is set up but when I try to go on a website it just says it is not connected to Internet. Do you follow the directions that it comes with? Or is there a trick to it? Could it be because I'm on El Capitan on my Mac?

**Comment by vinniejames** [comment]
I was also not able to get it running on 9.21. Xcode gave me a warning about the Build Settings, which I opted to Perform Changes. The app opened and connected to the ad hoc network, I updated the SOCKS proxy to match, but still no internet connection on my laptop

![screen shot 2016-02-08 at 7 58 01 pm](https://cloud.githubusercontent.com/assets/2112033/12907285/66257e56-ce9e-11e5-9f0f-c6cfd008b6e1.png)

**Comment by Rand-o** [comment]
Check out my Reddit post how to set up... Hopefully it can help you guys out https://www.reddit.com/r/iphone/comments/41cx00/sideload_a_tethering_app_for_your_iphone/

**Comment by vinniejames** [comment]
Thanks Rand-o! Tethering is working great, but it seems to have broken `localhost` for node apps on my machine while running. Any idea where I might start looking for a fix to this?

**Comment by OldManFern** [comment]
Thanks @Rand-o that worked. The worked for me. I never thought about setting the ip address.

**Comment by NickTullos** [comment]
using  @Rand-o ,@vinniejames , and the original directions combined i was able to get mine working on 9.2.1 on an iphone 6 plus as the server and an ipad air 2 as a client.

**Comment by mjpablo23** [comment]
has anyone tried this for ios 9.3?

**Comment by OldManFern** [comment]
Yes and it works. At least for me. But I have hence stop using it. I don't like the fact that I have to make a open network that anyone can join and do package listing.

**Comment by Rand-o** [comment]
@OldManFern What do you mean? You can have a password enabled on the Macbook/ Travel router just like any other wifi network you can set up...

**Comment by OldManFern** [comment]
How so? I thought we had to use ad-hoc. And as far as I could tell Apple took the ability to put a password on it. Mainly cause it uses WEP which is so easy to crack.

**Comment by Rand-o** [comment]
@OldManFern I guess you are right I thought there was one not seeing any settings for it on the Macbook... I do use a travel router instead though that you can put a password on... costs $10

**Comment by OldManFern** [comment]
Hmmmm travel router. That is a pretty smart way to get around the open network.

**Comment by Rand-o** [comment]
"TP-LINK TL-WR702N Wireless N150 Travel Router" has served me well, just used this in a hotel room not long ago works perfectly

**Comment by mjpablo23** [comment]
ah cool thanks, good to know for ios 9.3 and the network router.  do you need to use VPN so your carrier doesn't detect that you're tethering?  I have Cricket, and I've read mixed things about whether they care that you tether.

**Comment by Rand-o** [comment]
Yes, I use a VPN just to be safe I am with ATT

**Comment by rickyzhang82** [comment]
I haven't used this app for very long time.

I did experience the app crashed on iOS 9.3.2 frequently. But it was compiled in iOS 8.4 SDK. Does anyone compile it in iOS 9.3 SDK and has no issues to run it at all?

**Comment by rickyzhang82** [comment]
I confirmed that the App crash in iOS 9.3.3 with client running OS X 10.11.16. I will open a separate issue to investigate it.

**Comment by mjpablo23** [comment]
has anyone tested this for iOS 10?

**Comment by arronmabrey** [comment]
@mjpablo23 using it with ios 10.0.1 on iphone 7

**Comment by rickyzhang82** [comment]
If you are not interested in developing the app, I'd recommend you to deploy release version. If you enable debug, by default it uses NSLogger which may slow down iOS and use up battery for no good reason.

**Comment by mjpablo23** [comment]
Ah ok, good idea, thanks.  I will deploy to the release version
