### ISSUE TITLE
Bug: tethering app crashes

### ISSUE THREAD

**Issue by optimoid** [rickyzhang82/tethering#18]
* BUGFIX: Avoid 0 byte read which prevents future NSStreamEventHasBytesAvailable events from being delivered
	* Changed socket buffer to 4/8K - made possible after this fix

Added Core Proxy tests

Moved properties to protected header for test cases

See pull request: https://github.com/rickyzhang82/tethering/pull/15

**Comment by rickyzhang82** [comment]
Sorry, I haven't carefully reviewed your pull request. I inherited socks proxy code from the original project. I'm not familiar with that part. It will take me time to review and understand it.

I really appreciate your provide a test case. Could you give some details about 0 bytes read issue?

**Comment by optimoid** [comment]
Sure, so first thanks for this app, its the best one out there; but I found that it wasn't stable over a long period of time - crashing after a few hours under heavy use, or crashing instantly when connected to a fast 4G cellular network but when the phone was far from the router (poor wifi reception).

The bug is SocksProxy.mm:  line 510/478 in the event loop  `- (void)stream:(NSStream *)aStream handleEvent:(NSStreamEvent)eventCode)`

The problem is that the `remoteReceiveNetworkStream` (the stream from the server to the phone) can try and read 0 bytes into the buffer for `remoteReceiveNetworkStream` (the stream from the phone to the client). When this happens it is blocking `NSStreamEventHasSpaceAvailable` events from being received by the `sendnetworkStream` to clear the blockage. My fix is to make sure space is available by not reading from the `remoteReceiveNetworkStream` until space has been made in the `remoteReceiveNetworkStream`.


This bug appears to have been masked by whoever wrote the core proxy by allocating oversized socket buffers. Having fixed this bug I can then lower the size of the static buffer that is created for each socket from 100k/200k for the send/receive buffers to 4k/8k. The kernel will have put its own dynamically sized buffer around each end of the connection anyway so these buffers do not need to be any larger than 2 pages.

This drastically reduces the memory footprint of the app and allows it to support many more simultaneous connections. This change doesn't negatively affect the performance of the proxy (see the performance test case) and allows many more simultaneous connections.

**Comment by rickyzhang82** [comment]
There seems to be a bug when reading from remoteReceiveNetworkStream. It forgot to check if sendbuffer is full or not. When it is full, byteRead is 0. 

In this case, I'm not sure if read will block with 0 maxLength. I will use network link conditioner to simulate your case.

**Comment by rickyzhang82** [comment]
See my comment in #20
