### ISSUE TITLE
Apple developer account?

### ISSUE THREAD

**Issue by den-i** [rickyzhang82/tethering#23]
Do you still need a paid for apple developer account in order to create this app? Or can you use the free developer account?

**Comment by greatquux** [comment]
The free developer account works fine for me. But I recently discovered that the provisioning profile will only be valid for 3 months.  So when it expires, the application will refuse to start and you will have to compile and install it again.  Not a big deal, but something to be aware of.

**Comment by den-i** [comment]
@greatquux thank you. I was wondering if you could go into detail as to how to make it run. This is because I have followed the instructions but it does not seem to work
