### ISSUE TITLE
tsocks configuration

### ISSUE THREAD

**Issue by bjackson** [rickyzhang82/tethering#24]
Can this be used with tsocks to tunnel non-http connections? How did you configure it if so?

**Comment by Rand-o** [comment]
import os, sys
from select import select
#from scapy.all import IP

f = os.open("/dev/tun12", os.O_RDWR)
command = ("sudo ifconfig 169.254.101.100 169.254.101.177")
try:
    while 1:
        r = select([f],[],[])[0][0]
        if r == f:
            packet = os.read(f, 4000)
            print len(packet), packet
except KeyboardInterrupt:
    print "Stopped by user."


by running this script

**Comment by rickyzhang82** [comment]
tsocks doesn't resolve DNS, see https://github.com/rickyzhang82/tethering/wiki/Outstanding-issues-&-Workaround
