### ISSUE TITLE
Problem running the program (noob needs help)

### ISSUE THREAD

**Issue by den-i** [rickyzhang82/tethering#25]
so the instructions say the following

 * download the entire source code to a Mac

 * double click SOCKS.xcodeproj

<img width="961" alt="screen shot 2016-03-24 at 20 00 07" src="https://cloud.githubusercontent.com/assets/17938846/14029679/6422ba94-f1fb-11e5-92b6-90392b0ddac2.png">

 * in the left panel select Targers and then select SOCKS

<img width="1250" alt="screen shot 2016-03-24 at 20 02 23" src="https://cloud.githubusercontent.com/assets/17938846/14029816/2c536900-f1fc-11e5-88a5-2a729e0b5c6b.png">

(I am noob and I am stuck at this point. Could some one be kind enough to show the instructions with pictures from here on. I would be ever so grateful)

**P.s** 
should I change the bundle identifier name to e.g. com.tether.tethering?

(Thank you in advance)

**Comment by bradallred** [comment]
1. fix the provisioning issues by changing the bundle id to a unique one and selecting a valid profile. (click the "fix issue" button)
2. select your phone as the build destination (you currently have iphone 6s Plus simulator chosen)
3. click the play button

**Comment by den-i** [comment]
Thank you
