### ISSUE TITLE
I have tried to follow instructions but it's not wirking (noob in need of serious help)

### ISSUE THREAD

**Issue by den-i** [rickyzhang82/tethering#26]
Would someone be kind enough to make a vid of this working. E.g just a recording of them following the steps and the actual programme working. 

I have tried and tried but for some reason it's not working. 

I would be so great full. If you can not post a vid on here can you please send it to my email address:

Denydarks@hotmail.com

Thank you in advance

**Comment by Rand-o** [comment]
Sideload a "Tethering" app for your iPhone
http://reddit.com/r/iphone/comments/41cx00/sideload_a_tethering_app_for_your_iphone/

**Comment by rickyzhang82** [comment]
@Rand-o Thanks!
