### ISSUE TITLE
DNS ON iOS

### ISSUE THREAD

**Issue by kmddd59** [rickyzhang82/tethering#30]
The tethering works on all devices using the PAC file however the issue is that the only way to have it work is that you need to remove the DNS from your ip and make your ip static but make sure it's the same one you had on dhcp this was a issue the thing is that this is not shown in the introductions I also found out that newer macs can't use there own connections to get internet so a portable wifi hotspot is needed I just use a mifi without service it's just wifi witch is fine for me if it is possible to use USB witch I know it is I'd like to see that implemented in the app to improve speed

**Comment by rickyzhang82** [comment]
Are all punctuation key are broken in your keyboard?
