### ISSUE TITLE
Original code restricts port binding to 1080/3128. Not matching to comments.

### ISSUE THREAD

**Issue by raxcat** [rickyzhang82/tethering#31]
According to line 366 https://github.com/rickyzhang82/tethering/blob/master/SocksProxyController.mm#L366 

But currently the binding parts code are
https://github.com/rickyzhang82/tethering/blob/master/SocksProxyController.mm#L385

if both binding process failed, _startServer will be failed. 
👍

**Comment by raxcat** [comment]
I would suggest the following
   
```
  addr.sin_port   = htons(port);
        err = bind(fd, (const struct sockaddr *) &addr, sizeof(addr));
        success = (err == 0);
        if (success){
        }
        else{
            close(fd);
            fd = NULL;
            LOG_NETWORK_SOCKS(NSLOGGER_LEVEL_ERROR, @"Socks Server failed to bind port (%d), errono (%d)", port, errno);
            return;
        }

```

**Comment by rickyzhang82** [comment]
The port will be used to in socks.pac file. 

In addition, if the port is unpredictable, you have fix every single client in their proxy configuration. It is hassle.

**Comment by raxcat** [comment]
I see. Thank you.
