### ISSUE TITLE
doesn't work on iOS10

### ISSUE THREAD

**Issue by chlebta** [rickyzhang82/tethering#32]
Hello,
I've followed all the steps no crashs no bug but also I can't connect to internet I think it doesn't work on iOS10.
Have you tried it ?

**Comment by rickyzhang82** [comment]
No, can you enable the debug and see what went wrong?

**Comment by johnthepink** [comment]
I have been running it on iOS 10 without issue

**Comment by greatquux** [comment]
It's working for me in iOS 10.2.1, connecting from macOS 10.12.4.  In fact, works better than it ever did on 10.9.  (Maybe they fixed it in 10.10 or 10.11, I don't know.) Now I have no issues with DNS resolution after setting my system proxy information to use my iPhone for DNS resolution.  You may wish to note this in the wiki. 
Another note for the wiki - even if you leave SIP enabled, you can copy the binary you wish to socksify to your home directory or /tmp or some other directory that SIP doesn't protect, and then run it through socksify or tsocks or proxychains-ng (which is what I am using) and it will work great.

**Comment by rickyzhang82** [comment]
Thanks for your confirmation.
