### ISSUE TITLE
Problems Building

### ISSUE THREAD

**Issue by Jcaezza** [rickyzhang82/tethering#33]
When I try to build the application I get the error of a parse issue with an expected unqualified identifier. 
<img width="1400" alt="screen shot 2017-08-24 at 3 09 27 pm" src="https://user-images.githubusercontent.com/20116762/29684275-5a8fae66-88df-11e7-9475-bee20a7a69ce.png">

**Comment by rickyzhang82** [comment]
I clone from github repo today and build under XCode 8.3.3. It is error free.

**Comment by Jcaezza** [comment]
Thank you for the quick response. I was using the Xcode 9 Beta, so I guess that was why it wasn't working.

**Comment by rickyzhang82** [comment]
Thanks for reporting this. We will reopen it if it does happens in upcoming XCode 9.

**Comment by rickyzhang82** [comment]
I verified the issue today with XCode 9 update. It is caused by naming conflict with iOS 11 SDK. Fix in https://github.com/rickyzhang82/tethering/commit/486198f80fad83e94ca15dc5740e3fcde0a09b4c
