### ISSUE TITLE
won't build

### ISSUE THREAD

**Issue by kmddd59** [rickyzhang82/tethering#34]
Tethering project Group
Validate Project Settings Group
/Users/maefarris/Downloads/tethering-1.7/Tethering.xcodeproj Update to recommended settings
Tethering Group
Parse Issue Group
/Users/maefarris/Downloads/tethering-1.7/ttdnsd/ttdnsd.h:63:11: Expected unqualified-id
/Users/maefarris/Downloads/tethering-1.7/SocksProxyController.mm:23:9: In file included from /Users/maefarris/Downloads/tethering-1.7/SocksProxyController.mm:23:
/Users/maefarris/Downloads/tethering-1.7/SocksProxyController.h:26:10: In file included from /Users/maefarris/Downloads/tethering-1.7/SocksProxyController.h:26:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/usr/include/sys/param.h:102:18: Expanded from macro 'NOGROUP'
Asset Catalog Compiler Warning Group
/Users/maefarris/Downloads/tethering-1.7/Resources/Images.xcassets: A 1024x1024 app store icon is required for iOS apps
Semantic Issue Group
/Users/maefarris/Downloads/tethering-1.7/WebServer/HTTPResponseHandler.m:98:44: Unused parameter 'aRequest'
/Users/maefarris/Downloads/tethering-1.7/WebServer/HTTPResponseHandler.m:99:21: Unused parameter 'requestMethod'
/Users/maefarris/Downloads/tethering-1.7/WebServer/HTTPResponseHandler.m:100:15: Unused parameter 'requestURL'
/Users/maefarris/Downloads/tethering-1.7/WebServer/HTTPResponseHandler.m:101:31: Unused parameter 'requestHeaderFields'
/Users/maefarris/Downloads/tethering-1.7/SocksProxy.mm:187:36: Unused parameter 'streamName'
/Users/maefarris/Downloads/tethering-1.7/WebServer/PacFileResponse.m:46:44: Unused parameter 'aRequest'
/Users/maefarris/Downloads/tethering-1.7/WebServer/PacFileResponse.m:47:38: Unused parameter 'requestMethod'
/Users/maefarris/Downloads/tethering-1.7/WebServer/PacFileResponse.m:48:35: Unused parameter 'requestURL'
/Users/maefarris/Downloads/tethering-1.7/WebServer/PacFileResponse.m:49:42: Unused parameter 'requestHeaderFields'
/Users/maefarris/Downloads/tethering-1.7/MOButton.mm:40:1: Method possibly missing a [super awakeFromNib] call
/Users/maefarris/Downloads/tethering-1.7/MOButton.mm:71:22: Unused parameter 'aButton'
/Users/maefarris/Downloads/tethering-1.7/MOButton.mm:71:40: Unused parameter 'event'
/Users/maefarris/Downloads/tethering-1.7/MOButton.mm:76:24: Unused parameter 'aButton'
/Users/maefarris/Downloads/tethering-1.7/MOButton.mm:76:42: Unused parameter 'event'
/Users/maefarris/Downloads/tethering-1.7/WebServer/HTTPServer.m:169:1: Writable atomic property 'state' cannot pair a synthesized getter with a user defined setter
/Users/maefarris/Downloads/tethering-1.7/WebServer/HTTPServer.m:33:47: Setter and getter must both be synthesized, or both be user defined,or the property must be nonatomic
/Users/maefarris/Downloads/tethering-1.7/WebServer/HTTPServer.m:33:47: Property declared here
/Users/maefarris/Downloads/tethering-1.7/AncillaryCode/AppDelegate.mm:148:49: Unused parameter 'timer'
/Users/maefarris/Downloads/tethering-1.7/SocksProxyController.mm:562:57: Unused parameter 'n'
/Users/maefarris/Downloads/tethering-1.7/SocksProxyController.mm:631:55: Unused parameter 'controller'
/Users/maefarris/Downloads/tethering-1.7/SocksProxyController.mm:631:95: Unused parameter 'didLoadSuccessfully'
/Users/maefarris/Downloads/tethering-1.7/SocksProxyController.mm:635:64: Unused parameter 'controller'
/Users/maefarris/Downloads/tethering-1.7/SocksProxyController.mm:641:81: Unused parameter 'section'
Value Conversion Issue Group
/Users/maefarris/Downloads/tethering-1.7/SocksProxy.mm:315:22: Implicit conversion loses integer precision: 'unsigned long' to 'uint' (aka 'unsigned int')
/Users/maefarris/Downloads/tethering-1.7/SocksProxy.mm:495:13: Implicit conversion loses integer precision: 'long' to 'uint' (aka 'unsigned int')
/Users/maefarris/Downloads/tethering-1.7/ttdnsd/ttdnsd.mm:415:19: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
/Users/maefarris/Downloads/tethering-1.7/ttdnsd/ttdnsd.mm:500:19: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
/Users/maefarris/Downloads/tethering-1.7/ttdnsd/ttdnsd.mm:631:19: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
/Users/maefarris/Downloads/tethering-1.7/ttdnsd/ttdnsd.mm:734:31: Implicit conversion loses integer precision: 'unsigned long' to 'in_addr_t' (aka 'unsigned int')
/Users/maefarris/Downloads/tethering-1.7/ttdnsd/ttdnsd.mm:1029:31: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
/Users/maefarris/Downloads/tethering-1.7/ttdnsd/ttdnsd.mm:1061:24: Implicit conversion loses integer precision: 'ssize_t' (aka 'long') to 'int'
Format String Issue Group
/Users/maefarris/Downloads/tethering-1.7/SocksProxy.mm:331:101: Format specifies type 'int' but the argument has type 'long'
/Users/maefarris/Downloads/tethering-1.7/SocksProxy_Prefix.pch:30:116: Expanded from macro 'LOG_NETWORK_SOCKS'
/Users/maefarris/Downloads/tethering-1.7/AncillaryCode/AppDelegate.mm:175:43: Format string is not a string literal (potentially insecure)
/Users/maefarris/Downloads/tethering-1.7/SocksProxy_Prefix.pch:34:104: Expanded from macro 'LOG_GENERAL'
/Users/maefarris/Downloads/tethering-1.7/AncillaryCode/AppDelegate.mm:175:43: Treat the string as an argument to avoid this
Apple Mach-O Linker (ld) Error Group
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Dsymutil Error Group
: error: cannot parse the debug map for "/Users/maefarris/Library/Developer/Xcode/DerivedData/Tethering-dcxvlvxzucscfxbjdzqhavyjthsu/Build/Products/Debug-iphoneos/Tethering.app/Tethering": No such file or directory

**Comment by rickyzhang82** [comment]
I built it in XCode 9.3 today. I can replicate the same warnings you listed. But I can't replicate the link error. I can built the App.

**Comment by kmddd59** [comment]
Okies I got it built with the older Xcode it seems that it’s an issue with the new “beta” Xcode
