### ISSUE TITLE
IPA for iPhone/Windows 10

### ISSUE THREAD

**Issue by johnnyde94** [rickyzhang82/tethering#37]
Hello I was wondering if there was a way to create a IPA for use on iPhone, I changed the .zip to .ipa and got an error when using cydia impactor am I missing something? Secondly, windows 10 will not allow Ad-Hoc networking as my wifi card is a newer model (Intel AC-8265) is there a way around this. My set up is to want to use my Verizon iPhone with unlimited data to send wifi with my computer. Sorry if this is not the correct area to post a question like this.

**Comment by MrVas** [comment]
One workaround for the lack of Ad-Hoc networking is to use a USB powered ESP8266 module running in AP mode with your iOS device and computer wirelessly connected to it.

**Comment by rickyzhang82** [comment]
Get [a portable router](https://www.amazon.com/HooToo-Wireless-10400mAh-External-Performance/dp/B074LHG47K/ref=sr_1_6?ie=UTF8&qid=1545532452&sr=8-6&keywords=portable+router) and build a wifi network with your gadget and iPhone.

**Comment by 3117310** [comment]
你好，可以发一份1.8版本的ipa吗？不会构建
