### ISSUE TITLE
cant connect on ipad

### ISSUE THREAD

**Issue by sonicboom171** [rickyzhang82/tethering#39]
i've got all the steps so that i can connect to the lte connection on my phone on google chrome with switchyomega and setting the socks proxy. however i'm struggling on how to connect on my iPad the guide says to enter http://iphone_ip:8080/socks.pac with my socks proxy being 10.45.0.145 at port 3128 i enter http://10.45.0.145:8080/socks.pac into the iPad's auto proxy setting but it doesn't not work i feel like i may be doing something wrong but not sure what.

if someone could steer me in the right direction id greatly appreciate it

**Comment by rickyzhang82** [comment]
Can you download the socks.pac file from a computer, instead of your iPad?

**Comment by rickyzhang82** [comment]
I will close it since no response for a week. Please feel free to reopen it.
