### ISSUE TITLE
Stream Open Error

### ISSUE THREAD

**Issue by Bronus** [rickyzhang82/tethering#41]
Hello, i'm running windows 10 and have an iPhone XS. It works occasionally, and when it does its really good. I love using the tether app, but my main problem is when i get the Stream Open Error every 5 minutes. Is there any way to fix this and how do i debug the app using windows? i cant get Xcode.

**Comment by rickyzhang82** [comment]
How can you build and install the App?

**Comment by rickyzhang82** [comment]
Do you get the binary from somewhere? I saw another issue who claim to use Windows 10 as well. Please comment your situation in #40

**Comment by Bronus** [comment]
I had downloaded an ipa tethering app, i have it more stable now by assigning a static ip. But still receive a few stream open errors
