### ISSUE TITLE
Not working on windows 10

### ISSUE THREAD

**Issue by sooxiaotong** [rickyzhang82/tethering#46]
socks protocol not supported. Please give me some clues to solve this.

**Comment by rickyzhang82** [comment]
The app supports both socks5 and http. See [wiki configuration](https://github.com/rickyzhang82/tethering/wiki/Configuration).

Windows 10 seem to support socks protocol. See [here](https://www.reddit.com/r/techsupport/comments/4j0l35/windows_10_route_all_traffic_through_socks5_proxy/)

**Comment by sooxiaotong** [comment]
this issue should not be closed

**Comment by sooxiaotong** [comment]
@rickyzhang82   I'm using my phone as hotspot, both of my Mac and PC connect to it, but the windows one won't work. It shows the error below. I tried using proxifier, pac, and socks all showing the same error... 
![image](https://user-images.githubusercontent.com/13378059/68531914-9168fd80-0352-11ea-8fc5-54e576388b69.png)
