### ISSUE TITLE
Socks5 not working in windows 10 

### ISSUE THREAD

**Issue by Grantapus1** [rickyzhang82/tethering#50]
I’ve been using this perfectly on Mac with no Issues, however, I need it on my windows computer too. I’ve spent all weekend trying to do the stocks5 proxy on windows, without luck. I cannot find a way. Can you please tell me step by step how to configure this socks5 proxy on windows? Thank you so much!

**Comment by rickyzhang82** [comment]
See https://github.com/rickyzhang82/tethering/issues/47

**Comment by Grantapus1** [comment]
> See #47

Hi, this tells me pretty much nothing about what to do. How do I do the “pac file implementation”? Also, I already tried to specify socks5://my iPhone IP and it didn’t work. What am I missing? 

Thanks for your help and also thanks for developing and supporting this app.

**Comment by rickyzhang82** [comment]
1. The issue confirmed that in Windows 10 auto proxy works. But you need to use socks5.pac file.
1. You can also use packet capture tool like Wireshark in your client to see what went wrong.

**Comment by Grantapus1** [comment]
Hi, where do I download the pac file ? Thanks

**Comment by rickyzhang82** [comment]
Read https://github.com/rickyzhang82/tethering/wiki/Configuration

**Comment by rickyzhang82** [comment]
I assume everything is OK now.
