### ISSUE TITLE
Socks Server failed to bind port (1080), errono (48)

### ISSUE THREAD

**Issue by linzycumbia** [rickyzhang82/tethering#53]
After updating to iOS 14 I now receive this error upon launch:

> 15:28:48.0279      Main thread | Socks Server failed to bind port (1080), errono (48)
15:28:48.0328 Thread 7, name = (null) | 15:28:48.0279      Main thread | Socks Serve
15:28:48.0328 Thread 7, name = (null) | r failed to bind port (1080), errono (48)
15:28:48.0329 Thread 7, name = (null) | 15:28:48.0328 Thread 7, name = (null) | 15:28:48.0279      Main thread | Socks Serve
15:28:48.0329 Thread 7, name = (null) | 15:28:48.0328 Thread 7, name = (null) | r failed to bind port (1080), errono (48)
15:28:48.0329      Main thread | Server Stopped: Registration failed
15:28:48.0329      Main thread | Magic string was sent to terminate DNS server: 127.0.0.1.
15:28:48.0384      Main thread | Server Started
15:28:48.0384      Main thread | Starting DNS server...
15:28:48.0384      Main thread | DNS server thread is created.

The screen stops responding and a connection can't be established from a connected device (client). 

I also notice the Automatic Proxy field remains n/a instead of giving me a pac file url. Seems the server is unable to register and advertise with Bonjour. Anyone else encountered this issue?

![IMG_5CE5E1E830BB-1](https://user-images.githubusercontent.com/75213674/100546704-c5021880-3230-11eb-842b-f42bcf0f6d00.jpeg)

**Comment by rickyzhang82** [comment]
It runs fine in iOS 14.2 on my phone.

The socks sever tries to bind the port 1080, 3128 in the loop when starting socks server. It seems that it can bind to 3128 but failed to register Bonjour.

Could you add some log message  `LOG_NETWORK_SOCKS` below the registration process?

https://github.com/rickyzhang82/tethering/blob/7a1556c6884d3a37577d133f11690dd908b2acf3/SocksProxyController.mm#L477

**Comment by linzycumbia** [comment]
I added a log message

```
if (success) {
     self.netService = [[NSNetService alloc] initWithDomain:@"local" type:@"_socks._tcp." name:@"" port:port];
     success = (self.netService != nil);
     LOG_NETWORK_SOCKS(NSLOGGER_LEVEL_DEBUG, @"registered successfully %@", success ? @"YES" : @"NO");
}
if (success) {
        self.netService.delegate = self;
        [self.netService publishWithOptions:NSNetServiceNoAutoRename]; 
        // continues in -netServiceDidPublish: or -netService:didNotPublish: ...
        LOG_NETWORK_SOCKS(NSLOGGER_LEVEL_DEBUG, @"registered successfully %@", success ? @"YES" : @"NO");
    }
```
This resulted in:

> 17:13:13.0301      Main thread | Socks Server failed to bind port (1080), errono (48)
17:13:15.0653      Main thread | registered successfully YES
17:13:16.0601      Main thread | registered successfully YES

netService: didNotPublish: is still called even though success is returning True.

**Comment by linzycumbia** [comment]
By adding 

```
<key>NSBonjourServices</key>
	<array>
		<string>_socks._tcp.</string>
		<string>_socks._udp.</string>
	</array>
```

to the info.plist I resolved the registration failure error.

I'm still getting the binding error:

`19:26:24.0655      Main thread | Socks Server failed to bind port (1080), errono (48)`

**Comment by rickyzhang82** [comment]
Socks server binding error is expected if the port 1080 is taken by the other app. Thus, we have backup port like 3128. You could add more if you like. 

https://github.com/rickyzhang82/tethering/blob/7a1556c6884d3a37577d133f11690dd908b2acf3/SocksProxyController.mm#L411

It is a red herring.

Yet, I can't reproduce Bonjour issue without you plist hack.

**Comment by rickyzhang82** [comment]
Can you poke around the `errorDict` to see why without your hack?

https://github.com/rickyzhang82/tethering/blob/7a1556c6884d3a37577d133f11690dd908b2acf3/SocksProxyController.mm#L327

**Comment by linzycumbia** [comment]
errorDict contains

`NSNetServicesErrorCode = "-72008"`

Googling that code led me to this [https://developer.apple.com/forums/thread/659563#633366022](url)

**Comment by linzycumbia** [comment]
Ignoring the failure to bind error, I decided to try loading up apple.com over the proxy. The page loaded on my mac and then the app became unresponsive. It looks like thread 6 is trying to run another instance of Socks Server. Here is the log:

> 20:41:04.0071      Main thread | Socks Server failed to bind port (1080), errono (48)
20:41:04.0162      Main thread | Server Started
20:41:04.0162      Main thread | Starting DNS server...
20:41:04.0162      Main thread | DNS server thread is created.
20:41:04.0220 Thread 6, name = (null) | 20:41:04.0071      Main thread | Socks Server failed to bind port (1080), errono (48)
20:41:04.0220 Thread 6, name = (null) | 20:41:04.0162      Main thread | Server Started
20:41:04.0220 Thread 6, name = (null) | 20:41:04.0162      Main thread | Starting DNS server...
2020-11-29 15:41:04.820059-0500 Tethering[1269:188468] [connection] nw_connection_copy_connected_path [C1] Client called nw_connection_copy_connected_path on unconnected nw_connection
2020-11-29 15:41:04.854658-0500 Tethering[1269:188468] [] tcp_connection_is_cellular No connected path
20:41:04.0220 Thread 6, name = (null) | 20:41:04.0162      Main thread | DNS server thread is created.
20:41:04.0220 Thread 6, name = (null) | 20:41:04.0220 Thread 6, name = (null) | 20:41:04.0071      Main thread | Socks Server failed to bind port (1080), errono (48)
20:41:04.0220 Thread 6, name = (null) | 20:41:04.0220 Thread 6, name = (null) | 20:41:04.0162      Main thread | Server Started
20:41:04.0220 Thread 6, name = (null) | 20:41:04.0220 Thread 6, name = (null) | 20:41:04.0162      Main thread | Starting DNS server...
20:41:04.0776      Main thread | Accept connection 1 1
20:41:04.0854 Thread 6, name = (null) | 2020-11-29 15:41:04.820059-0500 Tethering[1269:188468] [connection] nw_connection_copy_connected_path [C1] Client called nw_connection_copy_connected_path on unconnected nw_connection
20:41:04.0854 Thread 6, name = (null) | 2020-11-29 15:41:04.854658-0500 Tethering[1269:188468] [] tcp_connection_is_cellular No connected path
20:41:04.0854      Main thread | Open C>P
20:41:04.0854      Main thread | Status: Opened connection
20:41:04.0854      Main thread | Open P>C
20:41:04.0854      Main thread | Status: Opened connection
20:41:04.0854      Main thread | Receive C>P
20:41:04.0854      Main thread | going to read C>P
20:41:04.0855      Main thread | Actually readReceiveNetwork read 3 for C>P
20:41:04.0855      Main thread | protocol 0 3
20:41:04.0855      Main thread | sendnetworkStream has NO space available for C>P
20:41:04.0855      Main thread | Send P>C
20:41:04.0855      Main thread | attempt to sendBuffer 2 for P>C
20:41:04.0855      Main thread | Actually sendBuffer write 2 for P>C
20:41:04.0855      Main thread | Send P>C
20:41:04.0855      Main thread | sendBuffer has no new data to send for P>C
20:41:04.0910      Main thread | Receive C>P
20:41:04.0910      Main thread | going to read C>P
20:41:04.0910      Main thread | Actually readReceiveNetwork read 20 for C>P
20:41:04.0910      Main thread | protocol 1 20
20:41:04.0910      Main thread | Status: www.apple.com:443
20:41:04.0910      Main thread | attempt to sendBuffer 20 for C>P
20:41:04.0910      Main thread | Actually sendBuffer write 20 for C>P
20:41:04.0910      Main thread | Send P>C www.apple.com:443
20:41:04.0911      Main thread | sendBuffer has no new data to send for P>C www.apple.com:443
20:41:04.0913      Main thread | Receive C>P www.apple.com:443
20:41:04.0913      Main thread | going to read C>P www.apple.com:443
20:41:04.0913      Main thread | Actually readReceiveNetwork read 517 for C>P www.apple.com:443
20:41:04.0913      Main thread | protocol 2 517
20:41:04.0913      Main thread | protocol 2 517
20:41:04.0913      Main thread | Wait for more data 2
20:41:05.0020      Main thread | Open S>P www.apple.com:443
20:41:05.0020      Main thread | Status: Opened connection
20:41:05.0020      Main thread | Open P>S www.apple.com:443
20:41:05.0020      Main thread | Status: Opened connection
20:41:05.0020      Main thread | Send P>S www.apple.com:443
20:41:05.0021      Main thread | attempt to sendremoteBuffer 517 for P>S www.apple.com:443
20:41:05.0021      Main thread | Actually sendremoteBuffer write 517 for P>S www.apple.com:443
20:41:05.0024      Main thread | Send P>S www.apple.com:443
20:41:05.0139      Main thread | Receive S>P www.apple.com:443
20:41:05.0139      Main thread | going to read S>P www.apple.com:443
20:41:05.0139      Main thread | Actually readRemoteReceiveNetwork read 1350 for S>P www.apple.com:443
20:41:05.0144      Main thread | attempt to sendBuffer 1350 for S>P www.apple.com:443
20:41:05.0144      Main thread | Actually sendBuffer write 1350 for S>P www.apple.com:443
20:41:05.0144      Main thread | Receive S>P www.apple.com:443
20:41:05.0144      Main thread | going to read S>P www.apple.com:443
20:41:05.0144      Main thread | Actually readRemoteReceiveNetwork read 2746 for S>P www.apple.com:443
20:41:05.0144      Main thread | attempt to sendBuffer 2746 for S>P www.apple.com:443
20:41:05.0145      Main thread | Actually sendBuffer write 2746 for S>P www.apple.com:443
20:41:05.0145      Main thread | Send P>C www.apple.com:443
20:41:05.0145      Main thread | sendBuffer has no new data to send for P>C www.apple.com:443
20:41:05.0211      Main thread | Receive S>P www.apple.com:443
20:41:05.0211      Main thread | going to read S>P www.apple.com:443
20:41:05.0211      Main thread | Actually readRemoteReceiveNetwork read 252 for S>P www.apple.com:443
20:41:05.0216      Main thread | attempt to sendBuffer 252 for S>P www.apple.com:443
20:41:05.0216      Main thread | Actually sendBuffer write 252 for S>P www.apple.com:443
20:41:05.0216      Main thread | Send P>C www.apple.com:443
20:41:05.0216      Main thread | sendBuffer has no new data to send for P>C www.apple.com:443
20:41:05.0221 Thread 6, name = (null) | 20:4
20:41:05.0228 Thread 6, name = (null) | 1:04.0220 Thread 6, name = (null) | 20:41:04.0162      Main thread | DNS server thread is created.
20:41:05.0228 Thread 6, name = (null) | 20:41:04.0220 Thread 6, name = (null) | 20:41:04.0220 Thread 6, name = (null) | 20:41:04.0071      Main thread | Socks Server failed to bind port (1080), errono (48)
20:41:05.0228 Thread 6, name = (null) | 20:41:04.0220 Thread 6, name = (null) | 20:41:04.0220 Thread 6, name = (null) | 20:41:04.0162      Main thread | Server Started
20:41:05.0228 Thread 6, name = (null) | 20:41:04.0220 Thread 6, name = (null) | 20:41:04.0220 Thread 6, name = (null) | 20:41:04.0162      Main thread | Starting DNS server...
20:41:05.0228 Thread 6, name = (null) | 20:41:04.0776      Main thread | Accept connection 1 1
20:41:05.0228 Thread 6, name = (null) | 20:41:04.0854 Thread 6, name = (null) | 2020-11-29 15:41:04.820059-0500 Tethering[1269:188468] [connection] nw_connection_copy_connected_path [C1] Client called nw_connection_copy_connected_path on unconnected nw_connection
20:41:05.0228 Thread 6, name = (null) | 20:41:04.0854 Thread 6, name = (null) | 2020-11-29 15:41:04.854658-0500 Tethering[1269:188468] [] tcp_connection_is_cellular No connected path
20:41:05.0228 Thread 6, name = (null) | 20:41:04.0854      Main thread | Open C>P
20:41:06.0243 Thread 6, name = (null) | name = (null) | 20:4
20:41:06.0243 Thread 6, name = (null) | 20:41:05.0228 Thread 6, name = (null) | 1:04.0220 Thread 6, name = (null) | 20:41:04.0162      Main thread | DNS server thread is created.
20:41:06.0243 Thread 6, name = (null) | 20:41:

**Comment by rickyzhang82** [comment]
This looks like your carrier blocking your connection rather than the app issue. I don't see receive end from the log.

**Comment by linzycumbia** [comment]
I don't even have to connect to the proxy for the app to freeze. Here is a the full log. I launched the app and tapped start, it logged all of this and then stopped responding.
[full_log.txt](https://github.com/rickyzhang82/tethering/files/5612877/full_log.txt)

**Comment by rickyzhang82** [comment]
I tested it as of Nov 29, 2020. I got some `Receive` and `Actually readReceiveNetowrk read` debug message.

If you want to debug more, compile NSLogger UI in Mac. It could filter by level and tag such as `network:socks`.

![Screen Shot 2020-11-29 at 4 32 00 PM](https://user-images.githubusercontent.com/3475933/100554100-81bf9e00-3260-11eb-8688-7454b9fcbd92.png)

**Comment by rickyzhang82** [comment]
Your log is incomplete. But you are on your own. I can't replicate the issue on my side.

I have hunch that your tethering may get banned by the mobile network carrier. Can you try VPN on your iPhone? This may circumvent censoring.

**Comment by linzycumbia** [comment]
Ok I will try VPN and try to find the source of the crash.

**Comment by linzycumbia** [comment]
VPN did not solve the issue.

**Comment by linzycumbia** [comment]
I have arrived at the same conclusion that my mobile carrier, Sprint (now part of T-Mobile), must be blocking this method of tethering. I wonder if the merge with T-Mobile is the reason, as I never had trouble with Sprint before. I'm just wondering how they can detect the tethered connection if the app is a proxy. Isn't all traffic disguised to be traffic originating from iOS and therefore undetectable? Without this app, Sprint allows me 500MB of tethering per month so I'm committed to finding a solution to this if it is possible.

**Comment by rickyzhang82** [comment]
Undetectable traffics is a strong assumption. I have done a research project last year to use DNN to classify encrypted network traffic that circumvent Communist China great firewall from other legitimate networks traffic. It turns out to be quite easy to achieve 0.01% type I error.

I’d recommend you to try on VPN first: install an OpenVPN sever at home and run OpenVPN client on your mobile gadget.

I doubt carrier would block VPN traffics

**Comment by linzycumbia** [comment]
I have managed to get the code working. I don't know if it is an issue with the iPhone 12/Pro but removing NSLogger and all code calls related to NSLogger solved the issue for me. I will clean up the code and make a fork of the project. If I have time I will really look into the reason why NSLogger was causing the app to crash for me.

**Comment by rickyzhang82** [comment]
I'm surprised NSLogger causes the issue. Although I haven't updated NSLogger for quite some time, I didn't spot any issues in compilation in latest XCode. 

Also, in your build if you set as `RELEASE`, it should not include NSLogger or NSLog at all. 

See https://github.com/rickyzhang82/tethering/blob/master/SocksProxy_Prefix.pch
