### ISSUE TITLE
All of the voice chat apps(that I have tried)won’t work

### ISSUE THREAD

**Issue by kajohnray** [rickyzhang82/tethering#55]
(I am pretty much network illiterate)

this app works great with my pc on pretty much anything however voice chat applications such as discord, Skype, even steam voice chat would not go through.

I used proxifier to setup the proxy, and allowed apps to go through the firewall and proxifier. I just can’t seem to troubleshoot this issue.

**Comment by kajohnray** [comment]
Other things that dont work are:Spotify
Most games' matchmaking service/server browsers

**Comment by rickyzhang82** [comment]
If the voice apps use UDP, it won't work. The current sock5 proxy doesn't support UDP.

Feel free to send a PR.
