### ISSUE TITLE
iOS 15 crashes

### ISSUE THREAD

**Issue by beren12** [rickyzhang82/tethering#57]
Crashing on iOS 15 for some reason. Part of the logs look like:

Nov  7 20:22:58 Aaaa runningboardd(RunningBoard)[32] <Notice>: Invalidating assertion 32-3488-134911 (target:application<net.mid-earth.Tethering.imac>) from originator [daemon<com.apple.SpringBoard>:3488]
Nov  7 20:22:58 Aaaa SpringBoard(FrontBoard)[3488] <Error>: Bootstrapping failed for <FBApplicationProcess: 0x121b97b40; application<net.mid-earth.Tethering.imac>:<invalid>> with error: <NSError: 0x28751a850; domain: RBSRequestErrorDomain; code: 5; reason: "Launch failed."> {    NSUnderlyingError = <NSError: 0x28751f660; domain: NSPOSIXErrorDomain; code: 85>;
Nov  7 20:22:58 aaa SpringBoard(FrontBoard)[3488] <Notice>: [application<net.mid-earth.Tethering.imac>:-1] Now flagged as pending exit for reason: Bootstrap failed

**Comment by KeeonTabrizi** [comment]
@beren12 is this still an issue for you on ios 15.x?

**Comment by beren12** [comment]
I haven't tried again but I don't see any new commits...

**Comment by rickyzhang82** [comment]
It works fine in iOS 15.3.1. I was using the app for hours without crashing.
