### ISSUE TITLE
Provide a release

### ISSUE THREAD

**Issue by beren12** [rickyzhang82/tethering#58]
Could you possibly provide an IPA that people can use to re-sign for their own devices without having to build?

**Comment by rickyzhang82** [comment]
No, please do it on your own.

**Comment by W9JYD** [comment]
@rickyzhang82 thats rude. Really?? Do it yourself??? What about us who use Windows pcs with Sideloadly or AltStore???

**Comment by rickyzhang82** [comment]
Note that I'm a developer who contributes my **free** time to maintain this project. I know no nothing about side load or alt store.

**Comment by mrfanch** [comment]
Ricky: Definitely a fan here. Thank you for maintaining the working code (not to mention, resurrecting the code from its unusable state long ago).
